### ISSUE TITLE
Test Suite for `equals()` and `hashCode()`

### ISSUE THREAD

**Issue by JesusMcCloud** [a-sit-plus/kmp-crypto#15]
We need to make sure our classes' correctly implement equals and hashcode.
We can only do that by creating explicit test suites bottom-up.

**Comment by JesusMcCloud** [comment]
started [here](https://github.com/a-sit-plus/kmp-crypto/tree/fix/equality)

**Comment by JesusMcCloud** [comment]
can be continued based on development branch

**Comment by n0900** [comment]
continuing implementation [here](https://github.com/a-sit-plus/kmp-crypto/tree/feature/extendedTestCases)
